// Generated by gencpp from file testing_rig_control/BulkGetItem.msg
// DO NOT EDIT!


#ifndef TESTING_RIG_CONTROL_MESSAGE_BULKGETITEM_H
#define TESTING_RIG_CONTROL_MESSAGE_BULKGETITEM_H

#include <ros/service_traits.h>


#include <testing_rig_control/BulkGetItemRequest.h>
#include <testing_rig_control/BulkGetItemResponse.h>


namespace testing_rig_control
{

struct BulkGetItem
{

typedef BulkGetItemRequest Request;
typedef BulkGetItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BulkGetItem
} // namespace testing_rig_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_rig_control::BulkGetItem > {
  static const char* value()
  {
    return "f0b74b4d53178e0d0ede26a30b687544";
  }

  static const char* value(const ::testing_rig_control::BulkGetItem&) { return value(); }
};

template<>
struct DataType< ::testing_rig_control::BulkGetItem > {
  static const char* value()
  {
    return "testing_rig_control/BulkGetItem";
  }

  static const char* value(const ::testing_rig_control::BulkGetItem&) { return value(); }
};


// service_traits::MD5Sum< ::testing_rig_control::BulkGetItemRequest> should match
// service_traits::MD5Sum< ::testing_rig_control::BulkGetItem >
template<>
struct MD5Sum< ::testing_rig_control::BulkGetItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::BulkGetItem >::value();
  }
  static const char* value(const ::testing_rig_control::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::BulkGetItemRequest> should match
// service_traits::DataType< ::testing_rig_control::BulkGetItem >
template<>
struct DataType< ::testing_rig_control::BulkGetItemRequest>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::BulkGetItem >::value();
  }
  static const char* value(const ::testing_rig_control::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_rig_control::BulkGetItemResponse> should match
// service_traits::MD5Sum< ::testing_rig_control::BulkGetItem >
template<>
struct MD5Sum< ::testing_rig_control::BulkGetItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::BulkGetItem >::value();
  }
  static const char* value(const ::testing_rig_control::BulkGetItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::BulkGetItemResponse> should match
// service_traits::DataType< ::testing_rig_control::BulkGetItem >
template<>
struct DataType< ::testing_rig_control::BulkGetItemResponse>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::BulkGetItem >::value();
  }
  static const char* value(const ::testing_rig_control::BulkGetItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_RIG_CONTROL_MESSAGE_BULKGETITEM_H
