// Generated by gencpp from file testing_rig_control/GetPosition.msg
// DO NOT EDIT!


#ifndef TESTING_RIG_CONTROL_MESSAGE_GETPOSITION_H
#define TESTING_RIG_CONTROL_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <testing_rig_control/GetPositionRequest.h>
#include <testing_rig_control/GetPositionResponse.h>


namespace testing_rig_control
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace testing_rig_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_rig_control::GetPosition > {
  static const char* value()
  {
    return "b532ace3b383dc4c9e64687156423ac0";
  }

  static const char* value(const ::testing_rig_control::GetPosition&) { return value(); }
};

template<>
struct DataType< ::testing_rig_control::GetPosition > {
  static const char* value()
  {
    return "testing_rig_control/GetPosition";
  }

  static const char* value(const ::testing_rig_control::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::testing_rig_control::GetPositionRequest> should match
// service_traits::MD5Sum< ::testing_rig_control::GetPosition >
template<>
struct MD5Sum< ::testing_rig_control::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::GetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::GetPositionRequest> should match
// service_traits::DataType< ::testing_rig_control::GetPosition >
template<>
struct DataType< ::testing_rig_control::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::GetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_rig_control::GetPositionResponse> should match
// service_traits::MD5Sum< ::testing_rig_control::GetPosition >
template<>
struct MD5Sum< ::testing_rig_control::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::GetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::GetPositionResponse> should match
// service_traits::DataType< ::testing_rig_control::GetPosition >
template<>
struct DataType< ::testing_rig_control::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::GetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_RIG_CONTROL_MESSAGE_GETPOSITION_H
