// Generated by gencpp from file testing_rig_control/SyncGetPosition.msg
// DO NOT EDIT!


#ifndef TESTING_RIG_CONTROL_MESSAGE_SYNCGETPOSITION_H
#define TESTING_RIG_CONTROL_MESSAGE_SYNCGETPOSITION_H

#include <ros/service_traits.h>


#include <testing_rig_control/SyncGetPositionRequest.h>
#include <testing_rig_control/SyncGetPositionResponse.h>


namespace testing_rig_control
{

struct SyncGetPosition
{

typedef SyncGetPositionRequest Request;
typedef SyncGetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGetPosition
} // namespace testing_rig_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_rig_control::SyncGetPosition > {
  static const char* value()
  {
    return "ee2edb71184f0d84eae62d21dcdef2b3";
  }

  static const char* value(const ::testing_rig_control::SyncGetPosition&) { return value(); }
};

template<>
struct DataType< ::testing_rig_control::SyncGetPosition > {
  static const char* value()
  {
    return "testing_rig_control/SyncGetPosition";
  }

  static const char* value(const ::testing_rig_control::SyncGetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::testing_rig_control::SyncGetPositionRequest> should match
// service_traits::MD5Sum< ::testing_rig_control::SyncGetPosition >
template<>
struct MD5Sum< ::testing_rig_control::SyncGetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::SyncGetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::SyncGetPositionRequest> should match
// service_traits::DataType< ::testing_rig_control::SyncGetPosition >
template<>
struct DataType< ::testing_rig_control::SyncGetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::SyncGetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_rig_control::SyncGetPositionResponse> should match
// service_traits::MD5Sum< ::testing_rig_control::SyncGetPosition >
template<>
struct MD5Sum< ::testing_rig_control::SyncGetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_rig_control::SyncGetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::SyncGetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_rig_control::SyncGetPositionResponse> should match
// service_traits::DataType< ::testing_rig_control::SyncGetPosition >
template<>
struct DataType< ::testing_rig_control::SyncGetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::testing_rig_control::SyncGetPosition >::value();
  }
  static const char* value(const ::testing_rig_control::SyncGetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_RIG_CONTROL_MESSAGE_SYNCGETPOSITION_H
